[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
trust_protocol = "CSBAc1SiMALr4rnuCoB17BsddzthB4RAhjibGvyt6p6S"

[programs.devnet]
trust_protocol = "CSBAc1SiMALr4rnuCoB17BsddzthB4RAhjibGvyt6p6S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
